from pptx.action import ActionSetting as ActionSetting
from pptx.dml.effect import ShadowFormat as ShadowFormat
from pptx.shared import ElementProxy as ElementProxy
from pptx.util import lazyproperty as lazyproperty

class BaseShape:
    def __init__(self, shape_elm, parent) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def click_action(self): ...
    @property
    def element(self): ...
    @property
    def has_chart(self): ...
    @property
    def has_table(self): ...
    @property
    def has_text_frame(self): ...
    @property
    def height(self): ...
    @height.setter
    def height(self, value) -> None: ...
    @property
    def is_placeholder(self): ...
    @property
    def left(self): ...
    @left.setter
    def left(self, value) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, value) -> None: ...
    @property
    def part(self): ...
    @property
    def placeholder_format(self): ...
    @property
    def rotation(self): ...
    @rotation.setter
    def rotation(self, value) -> None: ...
    def shadow(self): ...
    @property
    def shape_id(self): ...
    @property
    def shape_type(self) -> None: ...
    @property
    def top(self): ...
    @top.setter
    def top(self, value) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, value) -> None: ...

class _PlaceholderFormat(ElementProxy):
    @property
    def element(self): ...
    @property
    def idx(self): ...
    @property
    def type(self): ...
