from pptx.dml.line import LineFormat as LineFormat
from pptx.enum.shapes import MSO_SHAPE_TYPE as MSO_SHAPE_TYPE
from pptx.shapes.base import BaseShape as BaseShape
from pptx.util import Emu as Emu, lazyproperty as lazyproperty

class Connector(BaseShape):
    def begin_connect(self, shape, cxn_pt_idx) -> None: ...
    @property
    def begin_x(self): ...
    @begin_x.setter
    def begin_x(self, value) -> None: ...
    @property
    def begin_y(self): ...
    @begin_y.setter
    def begin_y(self, value) -> None: ...
    def end_connect(self, shape, cxn_pt_idx) -> None: ...
    @property
    def end_x(self): ...
    @end_x.setter
    def end_x(self, value) -> None: ...
    @property
    def end_y(self): ...
    @end_y.setter
    def end_y(self, value) -> None: ...
    def get_or_add_ln(self): ...
    def line(self): ...
    @property
    def ln(self): ...
    @property
    def shape_type(self): ...
