from pptx.dml.line import LineFormat as LineFormat
from pptx.enum.shapes import MSO_SHAPE as MSO_SHAPE, MSO_SHAPE_TYPE as MSO_SHAPE_TYPE, PP_MEDIA_TYPE as PP_MEDIA_TYPE
from pptx.shapes.base import BaseShape as BaseShape
from pptx.shared import ParentedElementProxy as ParentedElementProxy
from pptx.util import lazyproperty as lazyproperty

class _BasePicture(BaseShape):
    def __init__(self, pic, parent) -> None: ...
    @property
    def crop_bottom(self): ...
    @crop_bottom.setter
    def crop_bottom(self, value) -> None: ...
    @property
    def crop_left(self): ...
    @crop_left.setter
    def crop_left(self, value) -> None: ...
    @property
    def crop_right(self): ...
    @crop_right.setter
    def crop_right(self, value) -> None: ...
    @property
    def crop_top(self): ...
    @crop_top.setter
    def crop_top(self, value) -> None: ...
    def get_or_add_ln(self): ...
    def line(self): ...
    @property
    def ln(self): ...

class Movie(_BasePicture):
    def media_format(self): ...
    @property
    def media_type(self): ...
    @property
    def poster_frame(self): ...
    @property
    def shape_type(self): ...

class Picture(_BasePicture):
    @property
    def auto_shape_type(self): ...
    @auto_shape_type.setter
    def auto_shape_type(self, member) -> None: ...
    @property
    def image(self): ...
    @property
    def shape_type(self): ...

class _MediaFormat(ParentedElementProxy): ...
