from pptx.enum.shapes import MSO_SHAPE_TYPE as MSO_SHAPE_TYPE, PP_PLACEHOLDER as PP_PLACEHOLDER
from pptx.oxml.shapes.graphfrm import CT_GraphicalObjectFrame as CT_GraphicalObjectFrame
from pptx.oxml.shapes.picture import CT_Picture as CT_Picture
from pptx.shapes.autoshape import Shape as Shape
from pptx.shapes.graphfrm import GraphicFrame as GraphicFrame
from pptx.shapes.picture import Picture as Picture
from pptx.util import Emu as Emu

class _InheritsDimensions:
    @property
    def height(self): ...
    @height.setter
    def height(self, value) -> None: ...
    @property
    def left(self): ...
    @left.setter
    def left(self, value) -> None: ...
    @property
    def shape_type(self): ...
    @property
    def top(self): ...
    @top.setter
    def top(self, value) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, value) -> None: ...

class _BaseSlidePlaceholder(_InheritsDimensions, Shape):
    @property
    def is_placeholder(self): ...
    @property
    def shape_type(self): ...

class BasePlaceholder(Shape):
    @property
    def idx(self): ...
    @property
    def orient(self): ...
    @property
    def ph_type(self): ...
    @property
    def sz(self): ...

class LayoutPlaceholder(_InheritsDimensions, Shape): ...
class MasterPlaceholder(BasePlaceholder): ...
class NotesSlidePlaceholder(_InheritsDimensions, Shape): ...
class SlidePlaceholder(_BaseSlidePlaceholder): ...

class ChartPlaceholder(_BaseSlidePlaceholder):
    def insert_chart(self, chart_type, chart_data): ...

class PicturePlaceholder(_BaseSlidePlaceholder):
    def insert_picture(self, image_file): ...

class PlaceholderGraphicFrame(GraphicFrame):
    @property
    def is_placeholder(self): ...

class PlaceholderPicture(_InheritsDimensions, Picture): ...

class TablePlaceholder(_BaseSlidePlaceholder):
    def insert_table(self, rows, cols): ...
