from pptx.enum.action import PP_ACTION as PP_ACTION
from pptx.shapes import Subshape as Subshape
from pptx.util import lazyproperty as lazyproperty

class ActionSetting(Subshape):
    def __init__(self, xPr, parent, hover: bool = False) -> None: ...
    @property
    def action(self): ...
    def hyperlink(self): ...
    @property
    def target_slide(self): ...
    @target_slide.setter
    def target_slide(self, slide) -> None: ...

class Hyperlink(Subshape):
    def __init__(self, xPr, parent, hover: bool = False) -> None: ...
    @property
    def address(self): ...
    @address.setter
    def address(self, url) -> None: ...
