from .compat import is_string as is_string
from .util import lazyproperty as lazyproperty
from _typeshed import Incomplete

class Video:
    def __init__(self, blob, mime_type, filename) -> None: ...
    @classmethod
    def from_blob(cls, blob, mime_type, filename: Incomplete | None = None): ...
    @classmethod
    def from_path_or_file_like(cls, movie_file, mime_type): ...
    @property
    def blob(self): ...
    @property
    def content_type(self): ...
    @property
    def ext(self): ...
    @property
    def filename(self): ...
    def sha1(self): ...

SPEAKER_IMAGE_BYTES: Incomplete
