from pptx.opc.package import OpcPackage as OpcPackage
from pptx.opc.packuri import PackURI as PackURI
from pptx.parts.coreprops import CorePropertiesPart as CorePropertiesPart
from pptx.parts.image import Image as Image, ImagePart as ImagePart
from pptx.parts.media import MediaPart as MediaPart
from pptx.util import lazyproperty as lazyproperty

class Package(OpcPackage):
    def core_properties(self): ...
    def get_or_add_image_part(self, image_file): ...
    def get_or_add_media_part(self, media): ...
    def next_image_partname(self, ext): ...
    def next_media_partname(self, ext): ...
    @property
    def presentation_part(self): ...

class _ImageParts:
    def __init__(self, package) -> None: ...
    def __iter__(self): ...
    def get_or_add_image_part(self, image_file): ...

class _MediaParts:
    def __init__(self, package) -> None: ...
    def __iter__(self): ...
    def get_or_add_media_part(self, media): ...
