from pptx.shared import PartElementProxy as PartElementProxy
from pptx.slide import SlideMasters as SlideMasters, Slides as Slides
from pptx.util import lazyproperty as lazyproperty

class Presentation(PartElementProxy):
    @property
    def core_properties(self): ...
    @property
    def notes_master(self): ...
    def save(self, file) -> None: ...
    @property
    def slide_height(self): ...
    @slide_height.setter
    def slide_height(self, height) -> None: ...
    @property
    def slide_layouts(self): ...
    @property
    def slide_master(self): ...
    def slide_masters(self): ...
    @property
    def slide_width(self): ...
    @slide_width.setter
    def slide_width(self, width) -> None: ...
    def slides(self): ...
