class ElementProxy:
    def __init__(self, element) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    @property
    def element(self): ...

class ParentedElementProxy(ElementProxy):
    def __init__(self, element, parent) -> None: ...
    @property
    def parent(self): ...
    @property
    def part(self): ...

class PartElementProxy(ElementProxy):
    def __init__(self, element, part) -> None: ...
    @property
    def part(self): ...
