from _typeshed import Incomplete
from pptx.compat import to_unicode as to_unicode
from pptx.dml.fill import FillFormat as FillFormat
from pptx.enum.dml import MSO_FILL as MSO_FILL
from pptx.enum.lang import MSO_LANGUAGE_ID as MSO_LANGUAGE_ID
from pptx.enum.text import MSO_AUTO_SIZE as MSO_AUTO_SIZE, MSO_UNDERLINE as MSO_UNDERLINE
from pptx.oxml.simpletypes import ST_TextWrappingType as ST_TextWrappingType
from pptx.shapes import Subshape as Subshape
from pptx.text.fonts import FontFiles as FontFiles
from pptx.text.layout import TextFitter as TextFitter
from pptx.util import Centipoints as Centipoints, Emu as Emu, Pt as Pt, lazyproperty as lazyproperty

class TextFrame(Subshape):
    def __init__(self, txBody, parent) -> None: ...
    def add_paragraph(self): ...
    @property
    def auto_size(self): ...
    @auto_size.setter
    def auto_size(self, value) -> None: ...
    def clear(self) -> None: ...
    def fit_text(self, font_family: str = 'Calibri', max_size: int = 18, bold: bool = False, italic: bool = False, font_file: Incomplete | None = None) -> None: ...
    @property
    def margin_bottom(self): ...
    @margin_bottom.setter
    def margin_bottom(self, emu) -> None: ...
    @property
    def margin_left(self): ...
    @margin_left.setter
    def margin_left(self, emu) -> None: ...
    @property
    def margin_right(self): ...
    @margin_right.setter
    def margin_right(self, emu) -> None: ...
    @property
    def margin_top(self): ...
    @margin_top.setter
    def margin_top(self, emu) -> None: ...
    @property
    def paragraphs(self): ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...
    @property
    def vertical_anchor(self): ...
    @vertical_anchor.setter
    def vertical_anchor(self, value) -> None: ...
    @property
    def word_wrap(self): ...
    @word_wrap.setter
    def word_wrap(self, value) -> None: ...

class Font:
    def __init__(self, rPr) -> None: ...
    @property
    def bold(self): ...
    @bold.setter
    def bold(self, value) -> None: ...
    def color(self): ...
    def fill(self): ...
    @property
    def italic(self): ...
    @italic.setter
    def italic(self, value) -> None: ...
    @property
    def language_id(self): ...
    @language_id.setter
    def language_id(self, value) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, value) -> None: ...
    @property
    def size(self): ...
    @size.setter
    def size(self, emu) -> None: ...
    @property
    def underline(self): ...
    @underline.setter
    def underline(self, value) -> None: ...

class _Hyperlink(Subshape):
    def __init__(self, rPr, parent) -> None: ...
    @property
    def address(self): ...
    @address.setter
    def address(self, url) -> None: ...

class _Paragraph(Subshape):
    def __init__(self, p, parent) -> None: ...
    def add_line_break(self) -> None: ...
    def add_run(self): ...
    @property
    def alignment(self): ...
    @alignment.setter
    def alignment(self, value) -> None: ...
    def clear(self): ...
    @property
    def font(self): ...
    @property
    def level(self): ...
    @level.setter
    def level(self, level) -> None: ...
    @property
    def line_spacing(self): ...
    @line_spacing.setter
    def line_spacing(self, value) -> None: ...
    @property
    def runs(self): ...
    @property
    def space_after(self): ...
    @space_after.setter
    def space_after(self, value) -> None: ...
    @property
    def space_before(self): ...
    @space_before.setter
    def space_before(self, value) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text) -> None: ...

class _Run(Subshape):
    def __init__(self, r, parent) -> None: ...
    @property
    def font(self): ...
    def hyperlink(self): ...
    @property
    def text(self): ...
    @text.setter
    def text(self, str) -> None: ...
