from . import parse_xml as parse_xml
from .ns import nsdecls as nsdecls, qn as qn
from .xmlchemy import BaseOxmlElement as BaseOxmlElement, ZeroOrOne as ZeroOrOne
from _typeshed import Incomplete
from pptx.compat import to_unicode as to_unicode

class CT_CoreProperties(BaseOxmlElement):
    category: Incomplete
    contentStatus: Incomplete
    created: Incomplete
    creator: Incomplete
    description: Incomplete
    identifier: Incomplete
    keywords: Incomplete
    language: Incomplete
    lastModifiedBy: Incomplete
    lastPrinted: Incomplete
    modified: Incomplete
    revision: Incomplete
    subject: Incomplete
    title: Incomplete
    version: Incomplete
    @staticmethod
    def new_coreProperties(): ...
    @property
    def author_text(self): ...
    @author_text.setter
    def author_text(self, value) -> None: ...
    @property
    def category_text(self): ...
    @category_text.setter
    def category_text(self, value) -> None: ...
    @property
    def comments_text(self): ...
    @comments_text.setter
    def comments_text(self, value) -> None: ...
    @property
    def contentStatus_text(self): ...
    @contentStatus_text.setter
    def contentStatus_text(self, value) -> None: ...
    @property
    def created_datetime(self): ...
    @created_datetime.setter
    def created_datetime(self, value) -> None: ...
    @property
    def identifier_text(self): ...
    @identifier_text.setter
    def identifier_text(self, value) -> None: ...
    @property
    def keywords_text(self): ...
    @keywords_text.setter
    def keywords_text(self, value) -> None: ...
    @property
    def language_text(self): ...
    @language_text.setter
    def language_text(self, value) -> None: ...
    @property
    def lastModifiedBy_text(self): ...
    @lastModifiedBy_text.setter
    def lastModifiedBy_text(self, value) -> None: ...
    @property
    def lastPrinted_datetime(self): ...
    @lastPrinted_datetime.setter
    def lastPrinted_datetime(self, value) -> None: ...
    @property
    def modified_datetime(self): ...
    @modified_datetime.setter
    def modified_datetime(self, value) -> None: ...
    @property
    def revision_number(self): ...
    @revision_number.setter
    def revision_number(self, value) -> None: ...
    @property
    def subject_text(self): ...
    @subject_text.setter
    def subject_text(self, value) -> None: ...
    @property
    def title_text(self): ...
    @title_text.setter
    def title_text(self, value) -> None: ...
    @property
    def version_text(self): ...
    @version_text.setter
    def version_text(self, value) -> None: ...
