class NamespacePrefixedTag(str):
    def __new__(cls, nstag, *args): ...
    def __init__(self, nstag) -> None: ...
    @property
    def clark_name(self): ...
    @property
    def local_part(self): ...
    @property
    def nsmap(self): ...
    @property
    def nspfx(self): ...
    @property
    def nsuri(self): ...

def namespaces(*prefixes): ...
nsmap = namespaces

def nsdecls(*prefixes): ...
def nsuri(nspfx): ...
def qn(namespace_prefixed_tag): ...
