from ..enum.dml import MSO_FILL as MSO_FILL
from ..util import Emu as Emu, lazyproperty as lazyproperty
from .fill import FillFormat as FillFormat

class LineFormat:
    def __init__(self, parent) -> None: ...
    def color(self): ...
    @property
    def dash_style(self): ...
    @dash_style.setter
    def dash_style(self, dash_style) -> None: ...
    def fill(self): ...
    @property
    def width(self): ...
    @width.setter
    def width(self, emu) -> None: ...
