from _typeshed import Incomplete

class PackURI(str):
    def __new__(cls, pack_uri_str): ...
    @staticmethod
    def from_rel_ref(baseURI, relative_ref): ...
    @property
    def baseURI(self): ...
    @property
    def ext(self): ...
    @property
    def filename(self): ...
    @property
    def idx(self): ...
    @property
    def membername(self): ...
    def relative_ref(self, baseURI): ...
    @property
    def rels_uri(self): ...

PACKAGE_URI: Incomplete
CONTENT_TYPES_URI: Incomplete
