from ..text.text import Font as Font, TextFrame as TextFrame
from ..util import lazyproperty as lazyproperty

class DataLabels:
    def __init__(self, dLbls) -> None: ...
    def font(self): ...
    @property
    def number_format(self): ...
    @number_format.setter
    def number_format(self, value) -> None: ...
    @property
    def number_format_is_linked(self): ...
    @number_format_is_linked.setter
    def number_format_is_linked(self, value) -> None: ...
    @property
    def position(self): ...
    @position.setter
    def position(self, value) -> None: ...
    @property
    def show_category_name(self): ...
    @show_category_name.setter
    def show_category_name(self, value) -> None: ...
    @property
    def show_legend_key(self): ...
    @show_legend_key.setter
    def show_legend_key(self, value) -> None: ...
    @property
    def show_percentage(self): ...
    @show_percentage.setter
    def show_percentage(self, value) -> None: ...
    @property
    def show_series_name(self): ...
    @show_series_name.setter
    def show_series_name(self, value) -> None: ...
    @property
    def show_value(self): ...
    @show_value.setter
    def show_value(self, value) -> None: ...

class DataLabel:
    def __init__(self, ser, idx) -> None: ...
    def font(self): ...
    @property
    def has_text_frame(self): ...
    @has_text_frame.setter
    def has_text_frame(self, value) -> None: ...
    @property
    def position(self): ...
    @position.setter
    def position(self, value) -> None: ...
    @property
    def text_frame(self): ...
