from ..enum.chart import XL_LEGEND_POSITION as XL_LEGEND_POSITION
from ..text.text import Font as Font
from ..util import lazyproperty as lazyproperty

class Legend:
    def __init__(self, legend_elm) -> None: ...
    def font(self): ...
    @property
    def horz_offset(self): ...
    @horz_offset.setter
    def horz_offset(self, value) -> None: ...
    @property
    def include_in_layout(self): ...
    @include_in_layout.setter
    def include_in_layout(self, value) -> None: ...
    @property
    def position(self): ...
    @position.setter
    def position(self, position) -> None: ...
