from ..dml.chtfmt import ChartFormat as ChartFormat
from ..shared import ElementProxy as ElementProxy
from ..util import lazyproperty as lazyproperty

class Marker(ElementProxy):
    def format(self): ...
    @property
    def size(self): ...
    @size.setter
    def size(self, value) -> None: ...
    @property
    def style(self): ...
    @style.setter
    def style(self, value) -> None: ...
