from ..oxml.ns import qn as qn
from ..oxml.simpletypes import ST_BarDir as ST_BarDir, ST_Grouping as ST_Grouping
from ..util import lazyproperty as lazyproperty
from .category import Categories as Categories
from .datalabel import DataLabels as DataLabels
from .series import SeriesCollection as SeriesCollection

class _BasePlot:
    def __init__(self, xChart, chart) -> None: ...
    def categories(self): ...
    @property
    def chart(self): ...
    @property
    def data_labels(self): ...
    @property
    def has_data_labels(self): ...
    @has_data_labels.setter
    def has_data_labels(self, value) -> None: ...
    def series(self): ...
    @property
    def vary_by_categories(self): ...
    @vary_by_categories.setter
    def vary_by_categories(self, value) -> None: ...

class AreaPlot(_BasePlot): ...
class Area3DPlot(_BasePlot): ...

class BarPlot(_BasePlot):
    @property
    def gap_width(self): ...
    @gap_width.setter
    def gap_width(self, value) -> None: ...
    @property
    def overlap(self): ...
    @overlap.setter
    def overlap(self, value) -> None: ...

class BubblePlot(_BasePlot):
    @property
    def bubble_scale(self): ...
    @bubble_scale.setter
    def bubble_scale(self, value) -> None: ...

class DoughnutPlot(_BasePlot): ...
class LinePlot(_BasePlot): ...
class PiePlot(_BasePlot): ...
class RadarPlot(_BasePlot): ...
class XyPlot(_BasePlot): ...

def PlotFactory(xChart, chart): ...

class PlotTypeInspector:
    @classmethod
    def chart_type(cls, plot): ...
