import abc
from pptx.chart.datalabel import DataLabel as DataLabel
from pptx.chart.marker import Marker as Marker
from pptx.compat import Sequence as Sequence
from pptx.dml.chtfmt import ChartFormat as ChartFormat
from pptx.util import lazyproperty as lazyproperty

class _BasePoints(Sequence, metaclass=abc.ABCMeta):
    def __init__(self, ser) -> None: ...
    def __getitem__(self, idx): ...

class BubblePoints(_BasePoints):
    def __len__(self) -> int: ...

class CategoryPoints(_BasePoints):
    def __len__(self) -> int: ...

class Point:
    def __init__(self, ser, idx) -> None: ...
    def data_label(self): ...
    def format(self): ...
    def marker(self): ...

class XyPoints(_BasePoints):
    def __len__(self) -> int: ...
