from ..compat import BytesIO as BytesIO

class _BaseWorkbookWriter:
    def __init__(self, chart_data) -> None: ...
    @property
    def xlsx_blob(self): ...

class CategoryWorkbookWriter(_BaseWorkbookWriter):
    @property
    def categories_ref(self): ...
    def series_name_ref(self, series): ...
    def values_ref(self, series): ...

class XyWorkbookWriter(_BaseWorkbookWriter):
    def series_name_ref(self, series): ...
    def series_table_row_offset(self, series): ...
    def x_values_ref(self, series): ...
    def y_values_ref(self, series): ...

class BubbleWorkbookWriter(XyWorkbookWriter):
    def bubble_sizes_ref(self, series): ...
