from pptx.chart.chart import Chart as Chart
from pptx.opc.package import XmlPart as XmlPart
from pptx.parts.embeddedpackage import EmbeddedXlsxPart as EmbeddedXlsxPart
from pptx.util import lazyproperty as lazyproperty

class ChartPart(XmlPart):
    partname_template: str
    @classmethod
    def new(cls, chart_type, chart_data, package): ...
    def chart(self): ...
    def chart_workbook(self): ...

class ChartWorkbook:
    def __init__(self, chartSpace, chart_part) -> None: ...
    def update_from_xlsx_blob(self, xlsx_blob) -> None: ...
    @property
    def xlsx_part(self): ...
    @xlsx_part.setter
    def xlsx_part(self, xlsx_part) -> None: ...
