from pptx.opc.package import XmlPart as XmlPart
from pptx.opc.packuri import PackURI as PackURI
from pptx.parts.slide import NotesMasterPart as NotesMasterPart, SlidePart as SlidePart
from pptx.presentation import Presentation as Presentation
from pptx.util import lazyproperty as lazyproperty

class PresentationPart(XmlPart):
    def add_slide(self, slide_layout): ...
    @property
    def core_properties(self): ...
    def get_slide(self, slide_id): ...
    def notes_master(self): ...
    def notes_master_part(self): ...
    def presentation(self): ...
    def related_slide(self, rId): ...
    def related_slide_master(self, rId): ...
    def rename_slide_parts(self, rIds) -> None: ...
    def save(self, path_or_stream) -> None: ...
    def slide_id(self, slide_part): ...
